- backend/.docker/localstack/Dockerfile
- backend/.docker/mysql/Dockerfile
- backend/.docker/mysql/my.cnf
- backend/.env.example
- backend/.eslintrc.js
- backend/.gitignore
- backend/.prettierrc
- backend/README.md
- backend/docker-compose.yml
- backend/nest-cli.json
- backend/package.json
- backend/prisma/schema.prisma
- backend/src/app.controller.spec.ts
- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/app.service.ts
- backend/src/infrastructure/prisma/prisma.module.ts
- backend/src/infrastructure/prisma/prisma.service.ts
- backend/src/main.ts
- backend/tsconfig.build.json
- backend/tsconfig.json
- package-lock.json
> Backend environment building

- backend/package.json
- package-lock.json
close #23 
- 使い方
- 悩んでいること
- その他伝えたいこと
> add nestjs-zod

- .vscode/settings.json
- frontend/src/app/(app)/_component/container/contentContainer.tsx
- frontend/src/app/(app)/_component/recipeCard/RecipeCard.tsx
- frontend/src/app/(app)/_component/recipeCard/RecipeFavButton.tsx
- frontend/src/app/(app)/_component/recipeCard/index.ts
- frontend/src/app/(app)/layout.tsx
- frontend/src/app/(app)/search/_component/HotChef.tsx
- frontend/src/app/(app)/search/_component/HotRecipe.tsx
- frontend/src/app/(app)/search/_component/index.ts
- frontend/src/app/(app)/search/layout.tsx
- frontend/src/app/(app)/search/page.tsx
- frontend/tailwind.config.js
#15 
- 使い方
https://github.com/qin-team-recipe/05-recipe-app/assets/71167689/b8bdcbc5-4572-4aaf-ad10-417f6ec271e2
- 悩んでいること
- その他伝えたいこと
> 話題のレシピセクションを作成

- frontend/next.config.js
#17 
- next.config.jsにリダイレクトの設定を追加
- 使い方
- 悩んでいること
- その他伝えたいこと
> 「/」へのアクセス時に「/search」にリダイレクトさせる

- frontend/src/app/(app)/search/_component/ChefList.tsx
- frontend/src/app/(app)/search/_component/HotChefList.tsx
- frontend/src/app/(app)/search/_component/HotRecipeList.tsx
- frontend/src/app/(app)/search/_component/index.ts
- frontend/src/app/(app)/search/page.tsx
#32 
- シェフ一覧セクションを実装
- 注目のシェフと話題のレシピセクションのコンポーネント名を修正
- 使い方
- 悩んでいること
- その他伝えたいこと
> シェフ一覧セクションを作成

- frontend/.eslintrc.js
- frontend/prettier.config.js
- frontend/src/app/(app)/_component/bottomNav/BottomNavBar.tsx
- frontend/src/app/(app)/_component/bottomNav/BottomNavItem.test.tsx
- frontend/src/app/(app)/_component/bottomNav/BottomNavItem.tsx
- frontend/src/app/(app)/_component/chefCard/ChefCard.tsx
- frontend/src/app/(app)/_component/chefCard/ChefInfo.tsx
- frontend/src/app/(app)/_component/container/contentContainer.tsx
- frontend/src/app/(app)/_component/header/PageDetailHeader.tsx
- frontend/src/app/(app)/_component/header/SectionHeader.test.tsx
- frontend/src/app/(app)/_component/header/SectionHeader.tsx
- frontend/src/app/(app)/_component/icon/SearchSvg.tsx
- frontend/src/app/(app)/_component/recipeCard/RecipeFavButton.tsx
- frontend/src/app/(app)/_component/twoTab/TwoTab.tsx
- frontend/src/app/(app)/layout.tsx
- frontend/src/app/(app)/search/_component/ChefList.tsx
- frontend/src/app/(app)/search/_component/HotChefList.tsx
- frontend/src/app/(app)/search/layout.tsx
- frontend/src/app/(app)/search/page.tsx
- frontend/src/app/_component/ScrollAreaWrapper.test.tsx
- frontend/src/app/_component/ScrollAreaWrapper.tsx
- frontend/tailwind.config.js
#48 
- next-page-testerやreact-hooks-testing-libraryがApp RouterとReact v18に対応していなかったため、
ページ遷移はPlaywriteを使わないとダメかも？
- 使い方
- 悩んでいること
- その他伝えたいこと
> タブコンポーネントの簡易的なテストコードを追加

- frontend/src/app/(app)/_component/icon/SearchSvg.tsx
- frontend/src/app/(app)/search/_component/SearchHeader.tsx
- frontend/src/app/(app)/search/_lib/TwoTabLinkList.ts
- frontend/src/app/(app)/search/_lib/helper.ts
- frontend/src/app/(app)/search/_lib/index.ts
- frontend/src/app/(app)/search/chef/page.tsx
- frontend/src/app/(app)/search/layout.tsx
- frontend/src/app/(app)/search/recipe/page.tsx
#38 
- 使い方
https://github.com/qin-team-recipe/05-recipe-app/assets/71167689/cbbc6b21-ccc5-4f38-b13f-cd37947768c9
- 悩んでいること
- その他伝えたいこと
> 検索フォームの大枠を実装

- frontend/src/app/(app)/_component/chefCard/ChefCard.tsx
- frontend/src/app/(app)/_component/chefCard/ChefImg.tsx
- frontend/src/app/(app)/_component/chefCard/ChefInfo.tsx
- frontend/src/app/(app)/_component/recipeCard/RecipeCard.tsx
- frontend/src/app/(app)/search/_component/ChefList.tsx
- frontend/src/app/(app)/search/_component/HotChefList.tsx
- frontend/src/app/(app)/search/_component/HotRecipeList.tsx
#58 
- 使い方
- 悩んでいること
- その他伝えたいこと
> 丸形のシェフカードを実装

- backend/src/entity/user-auth-provider.entity.ts
- backend/src/entity/user.entity.ts
- backend/src/infrastructure/repository/user-auth-provider/create.spec.ts
- backend/src/infrastructure/repository/user-auth-provider/repository.module.ts
- backend/src/infrastructure/repository/user-auth-provider/repository.ts
- backend/src/infrastructure/repository/user-profile/paginate.spec.ts
- backend/src/infrastructure/repository/user-profile/repository.ts
- backend/src/infrastructure/repository/user/create-with-auth-provider.spec.ts
- backend/src/infrastructure/repository/user/find-by-email.spec.ts
- backend/src/infrastructure/repository/user/repository.ts
- backend/src/usecase/user/usecase.module.ts
close #67
- 使い方
- 悩んでいること
- その他伝えたいこと
> Create User Auth Provider Repository

- .github/workflows/ci.yml
- backend/.eslintrc.js
- backend/src/infrastructure/repository/prisma-error-handling.ts
- backend/src/usecase/user/usecase.ts
- backend/src/utils/exception/database-connection.error.ts
- backend/src/utils/exception/invalid-args.error.ts
- backend/src/utils/exception/query-execution.error.ts
- backend/src/utils/logger/custom-logger.service.ts
- package-lock.json
- package.json
タスクのURLをGitHubProjectからコピーしてペースト
- 使い方
- 悩んでいること
- その他伝えたいこと
> Update CI and Lint

- frontend/src/app/(app)/_component/header/PageHeader.tsx
- frontend/src/app/(app)/_component/header/index.ts
- frontend/src/app/(app)/favorite/_component/FavoritePageHeader.tsx
- frontend/src/app/(app)/favorite/_component/index.ts
- frontend/src/app/(app)/favorite/page.tsx
#88 
- 使い方
- 悩んでいること
- その他伝えたいこと
> ページヘッダーの共通コンポーネントを作成

- frontend/src/app/(app)/_component/header/PageHeader.tsx
#94 
- 使い方
- 悩んでいること
- その他伝えたいこと
> PageHeaderコンポーネントのtitleのパターン追加

- frontend/src/app/(app)/favorite/_component/FavoritePageHeader.tsx
- frontend/src/app/(app)/myPage/_component/MyPageHeader.tsx
- frontend/src/app/(app)/myPage/_component/index.ts
- frontend/src/app/(app)/myPage/page.tsx
#83 
- 使い方
https://github.com/qin-team-recipe/05-recipe-app/assets/71167689/f819dbe1-7234-4f1d-97a6-6c4ac3288f2e
- 悩んでいること
- その他伝えたいこと
> お気に入り画面←→マイページ画面のルーティング

- frontend/src/app/(app)/_component/backButton/BackButton.tsx
- frontend/src/app/(app)/_component/header/PageDetailHeader.tsx
- frontend/src/app/(app)/myPage/_component/MyPageHeader.tsx
#99 
- レシピ詳細等の画像に重なっている場合の戻るボタンのスタイルが更新にともなう対応
- 使い方
- 悩んでいること
- その他伝えたいこと
> 戻るボタンのスタイルパターンを追加

- frontend/src/app/(app)/_component/header/PageDetail.types.ts
- frontend/src/app/(app)/_component/header/index.ts
- frontend/src/app/(app)/chef/[chefId]/_component/ChefPageDetail.tsx
- frontend/src/app/(app)/chef/[chefId]/link/page.tsx
- frontend/src/app/(app)/chef/[chefId]/page.tsx
- frontend/src/app/(app)/myPage/_component/MyPageDetail.tsx
- frontend/src/app/(app)/myPage/page.tsx
#112 
- 使い方
- 悩んでいること
- その他伝えたいこと
> リンクアイコンの表示

- frontend/package.json
- frontend/src/app/(app)/myPage/_component/MyPageDDMenu.tsx
- frontend/src/app/(app)/myPage/_component/MyPageDetail.tsx
- frontend/src/app/(app)/myPage/_component/index.ts
- frontend/src/app/_component/DDMenuWrapper.tsx
- frontend/src/app/_component/index.ts
- package-lock.json
#110 
メニューの見た目だけ実装しました。
クリックイベントは未実装です。
他のページでも使えるように型定義しましたが、書き方があっているか確認お願いします。
https://github.com/qin-team-recipe/05-recipe-app/assets/76086827/a3e632c2-db70-43d6-98e7-246fe3d3abf0
> ドロップダウンメニュー作成

- frontend/src/app/(app)/_component/header/PageDetail.types.ts
- frontend/src/app/(app)/_component/header/index.ts
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_component/MyRecipePageDetail.tsx
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_component/index.ts
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_lib/index.ts
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_lib/tabLinkList.ts
- frontend/src/app/(app)/myRecipe/[myRecipeId]/page.tsx
- frontend/src/app/(app)/myRecipe/[myRecipeId]/recipeItem/page.tsx
- frontend/src/app/(app)/recipe/[recipeId]/_component/RecipePageDetail.tsx
- frontend/src/app/(app)/recipe/[recipeId]/_component/index.ts
- frontend/src/app/(app)/recipe/[recipeId]/_lib/tabLinkList.ts
- frontend/src/app/(app)/recipe/[recipeId]/link/page.tsx
- frontend/src/app/(app)/recipe/[recipeId]/page.tsx
- frontend/src/app/(app)/recipe/[recipeId]/recipeItem/page.tsx
#114 
#122 
- 使い方
- 悩んでいること
- その他伝えたいこと
> マイレシピ詳細画面の作成

- frontend/src/app/(app)/myPage/_component/MyPageDDMenu.tsx
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_component/MyRecipeDDMenu.tsx
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_component/MyRecipePageDetail.tsx
close #116 
- 公開or非公開 でメニュー内容を出し分ける
「公開中」の場合
「非公開」の場合
> マイレシピ画面のドロップダウンメニュー作成

- frontend/src/app/(app)/myRecipe/add/_component/AddMyRecipePageHeader.test.tsx
- frontend/src/app/(app)/myRecipe/add/_component/AddMyRecipePageHeader.tsx
- frontend/src/app/(app)/myRecipe/add/_component/index.ts
- frontend/src/app/(app)/myRecipe/add/page.tsx
#128 
- マイレシピ追加画面のページヘッダーを作成
- 使い方
- 悩んでいること
- その他伝えたいこと
> feat: マイレシピ追加画面のページヘッダー

- frontend/src/app/(app)/myPage/_component/MyPageDDMenu.tsx
- frontend/src/app/(app)/myRecipe/[myRecipeId]/_component/MyRecipeDDMenu.tsx
- frontend/src/app/(app)/shopping/_component/ShoppingPageHeader.tsx
- frontend/src/app/(app)/shopping/_component/index.ts
- frontend/src/app/(app)/shopping/page.tsx
close #132 
- 使い方
- 悩んでいること
- その他伝えたいこと
> 買い物リストページヘッダー作成

- backend/src/entity/recipe.entity.ts
- backend/src/infrastructure/repository/recipe/delete.spec.ts
- backend/src/infrastructure/repository/recipe/repository.ts
recipeの削除も実装しましたので、ご確認お願い致します！
- recipeの削除関数作成
- テストの作成
> Create delete recipe

- backend/prisma/schema.prisma
- backend/src/entity/follow.entity.ts
- backend/src/infrastructure/repository/follow/create.spec.ts
- backend/src/infrastructure/repository/follow/delete.spec.ts
- backend/src/infrastructure/repository/follow/find-by-followed-id.spec.ts
- backend/src/infrastructure/repository/follow/repository.module.ts
- backend/src/infrastructure/repository/follow/repository.ts
close #144 
- Followのmodelにコメント追加（FollowerとFollowedの違いが分かりづらい為）
> Create Follow Repository 

- frontend/src/app/(app)/shopping/_component/RecipeItemWithChecked.tsx
- frontend/src/app/(app)/shopping/_component/ShoppingItem.tsx
- frontend/src/app/(app)/shopping/_component/ShoppingListDDMenu.tsx
- frontend/src/app/(app)/shopping/_component/ToBuyListBlock.tsx
- frontend/src/app/(app)/shopping/_component/index.ts
- frontend/src/app/(app)/shopping/layout.tsx
- frontend/src/app/(app)/shopping/page.tsx
> 買い物リストブロックの作成

- frontend/src/app/(app)/shopping/page.tsx
- frontend/src/mock/api/index.ts
- frontend/src/mock/api/shopping.ts
close #158 
- 買い物リストのmockデータをmock/配下へ切り出した
他のmockデータと同じようにしたつもりです！
> [買い物リスト画面]mockデータの切り出し

- frontend/src/app/(app)/myRecipe/add/_component/InstructionDDMenu.tsx
- frontend/src/app/(app)/myRecipe/add/_component/index.ts
- frontend/src/app/(app)/myRecipe/add/_lib/MyRecipeAddProvider.tsx
- frontend/src/app/(app)/myRecipe/add/_lib/index.ts
- frontend/src/app/(app)/myRecipe/add/page.tsx
- frontend/src/app/_component/DDMenuWrapper.tsx
#153 
- 使い方
- 悩んでいること
- その他伝えたいこと
> 作り方にDDMenuを追加

- backend/src/infrastructure/repository/recipe/find-many-by-user-id.spec.ts
- backend/src/infrastructure/repository/recipe/pickup-list.spec.ts
- frontend/src/app/(app)/favorite/_component/FavoriteChefList.tsx
- frontend/src/app/(app)/favorite/_component/FavoriteRecipeList.tsx
- frontend/src/app/(app)/favorite/_component/LatestRecipeList.tsx
- frontend/src/app/(app)/favorite/api/chefs/route.ts
- frontend/src/app/(app)/favorite/api/favoriteRecipes/route.ts
- frontend/src/app/(app)/favorite/api/latestRecipes/route.ts
- frontend/src/app/(app)/favorite/page.tsx
タスクのURLをGitHubProjectからコピーしてペースト
- シェフ一覧をRoute Handlerから取得
- 新着レシピ一覧をRoute Handlerから取得
- お気に入りレシピ一覧をRoute Handlerから取得
- 使い方
https://gyazo.com/2922130ef1de0088abe798c4f291002f
すみません！ネットワークの調子悪くてgyazoリンクで失礼します。
- 悩んでいること
- その他伝えたいこと
> feat/お気に入りページのモックデータをRoute Handlersに置換

- frontend/src/app/(app)/search/_component/SearchHeader.tsx
- frontend/src/app/(app)/search/_lib/tabLinkList.ts
- frontend/src/app/(app)/search/chef/page.tsx
- frontend/src/app/(app)/search/recipe/page.tsx
タスクのURLをGitHubProjectからコピーしてペースト
- SearchHeader周りのクエリパラメータの取り扱いを修正
- 使い方
- 悩んでいること
- その他伝えたいこと
> SearchHeader周りのクエリパラメータの取り扱いを修正

- frontend/src/app/(app)/_component/recipeCard/RecipeCard.tsx
- frontend/src/app/(app)/search/_component/SearchHeader.tsx
- frontend/src/app/(app)/search/api/pickupRecipes/route.ts
- frontend/src/app/(app)/search/recipe/pickup/page.tsx
タスクのURLをGitHubProjectからコピーしてペースト
- このプルリクエストにて何をしたのか？
- 使い方
- 悩んでいること
- その他伝えたいこと
> feat: add pickup recipes
